export enum VideoActionTypes {
  PLAY_VIDEO = "PLAY_VIDEO",
  PAUSE_VIDEO = "PAUSE_VIDEO",
  MUTE_VIDEO = "MUTE_VIDEO",
  UNMUTE_VIDEO = "UNMUTE_VIDEO",
  VIDEO_MOUSEENTER = "VIDEO_MOUSEENTER",
  VIDEO_MOUSELEAVE = "VIDEO_MOUSELEAVE",
  VIDEO_INITIAL_STATE = "VIDEO_INITIAL_STATE",
}
